#r "paket:
nuget FSharp.Core 4.5.0.0
nuget FSharp.Data //"
#load "./.fake/FetchTestData.fsx/intellisense.fsx"

open FSharp.Data
open System.Text
open System.IO

type Pins = CsvProvider<"TestDataTemplate.csv">

let getPins url =
    async {
        let! pins = Pins.AsyncLoad url
        return 
            pins.Rows
            |> Seq.map (fun r -> r.Testpersonnummer |> string)
    }

let header = """// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
module internal ActiveLogin.Identity.Swedish.TestData.AllPins
    let allPins = 
        [|
"""

let footer = """        |]"""

let sb = StringBuilder()
sb.Append(header)

[ "https://skatteverket.entryscape.net/store/9/resource/149"
  "https://skatteverket.entryscape.net/store/9/resource/535"
  "https://skatteverket.entryscape.net/store/9/resource/686" ]
|> List.map getPins
|> Async.Parallel
|> Async.RunSynchronously
|> Seq.concat
|> Seq.iter (fun pin -> sb.AppendLine(sprintf "            \"%s\"" pin) |> ignore)

sb.Append(footer)

File.WriteAllText("AllPins.fs", sb.ToString())
