// Run the script with dotnet fsi: 'dotnet fsi FetchCoordinationTestData.fsx'

#r "nuget: FSharp.Data"
#load "./FetchCommon.fs"

open FSharp.Data
open System
open System.Text
open System.IO
open FetchCommon

type TestData = CsvProvider<const(__SOURCE_DIRECTORY__ + "/CoordinationTestDataTemplate.csv")>

let [<Literal>] DayOffset = 60
let getCoordNums url =
    async {
        let! nums = TestData.AsyncLoad url
        return
            nums.Rows
            |> Seq.map (fun r -> r.TestSamordningsnummer)
    }

let isValidCoordNum (str: string) =
    let year = int str.[0..3]
    let month = int str.[4..5]
    let day = int str.[6..7]
    let daysInMonth = if month = 0 then 31 else DateTime.DaysInMonth(year, month)
    let isValid = day >= DayOffset && day <= DayOffset + daysInMonth
    if not isValid then printfn "Found invalid CoordinationNum: %s" str
    isValid

let nums =
    [ "https://skatteverket.entryscape.net/store/9/resource/154"
      "https://skatteverket.entryscape.net/store/9/resource/1027"
      "https://skatteverket.entryscape.net/store/9/resource/1272"
      "https://skatteverket.entryscape.net/store/9/resource/1581"
      "https://skatteverket.entryscape.net/store/9/resource/1887" ]
    |> List.map getCoordNums
    |> Async.Parallel
    |> Async.RunSynchronously
    |> Seq.concat
    |> Seq.sort
    |> Seq.map string
    |> Seq.filter isValidCoordNum


let header = """// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
module internal ActiveLogin.Identity.Swedish.TestData.AllCoordNums
    let allCoordNums =
        [|
"""

let footer = """        |]"""

let sb = StringBuilder()
sb.Append(header)

nums
|> Seq.iter (toStringTuple >> appendLine sb)
sb.Append(footer)
File.WriteAllText("AllCoordNums.fs", sb.ToString())
